# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmZjZTRlZWJlYzEyMGMyNDVlYjkyZGJiNGE0Yjg2MzkzNTRhYWU4ODJlYmI1MDEzNWNlMDMwNzEyM2ZkOTE4YzNkZjVmOGIxN2U1YzgxNDJhZjE3NjIzYjAyODc4MzU2YjU0NDE4NzU0YjljY2Y1MmQ1ZjExMTUxOTUwMWVlZjE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
